services:
  - type: web
    name: waf-application
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn "main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
