services:
  - type: web
    name: waf-application
    env: python
    buildCommand: |
      python -m venv --clear .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install --upgrade numpy scipy joblib scikit-learn
      pip install -r requirements.txt
    startCommand: gunicorn "main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
