services:
  - type: web
    name: waf-application
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import numpy; print('NumPy version:', numpy.__version__)"
      python -c "import sklearn; print('Scikit-learn version:', sklearn.__version__)"
    startCommand: gunicorn "main:app"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
